### ISSUE TITLE
Tidying up main.min.css

### ISSUE THREAD

**Issue by ghost** [stevelacey/ghostium#3]
The style sheet for this theme is a giant block of text. Any interest in me forking and tidying it up a bit when I get a chance? Otherwise, it would be a pretty simple task someone could take on.

**Comment by stevelacey** [comment]
I think you missed https://github.com/stevelacey/ghostium/tree/master/src/assets/_scss

**Comment by ghost** [comment]
I sure did @stevelacey. Nice work, and thanks for keeping this theme supported!
